# The runtime your application uses. App Engine will use a recent, stable version.
runtime: python313

# The entrypoint command that starts your web server.
# App Engine automatically sets the $PORT environment variable.
# We use uvicorn to run our Starlette application.
entrypoint: uvicorn app:app --host 0.0.0.0 --port $PORT

# Environment variables that will be available to your application.
# IMPORTANT: Do not commit sensitive secrets like this to your repository.
# For production, use a secret management tool. For this example, we set it here.
env_variables:
  APP_SECRET: "YOUR_APP_SECRET_HERE"
  # Note: Google Cloud authentication is handled automatically by the environment,
  # so you don't need to set GOOGLE_APPLICATION_CREDENTIALS here.
